name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cleanup
    - name: Publish to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: frogfishio/dev
        username: frogfishio
        password: ${{ secrets.DOCKERHUB_SECRET }}